<?php

define('DATABASE_HOST_NAME',"YOUR_SERVER_HOST");
define('DATABASE_NAME','YOUR_DATABASE_NAME');
define('DATABASE_USER','YOUR_DATABASE_USER_NAME');
define('DATABASE_PASSWORD','YOUR_DATABASE_USER_PASSWORD');

?>